# Generated by Django 2.1.4 on 2020-03-26 03:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('theme', models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('description', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='anonymity', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('averageScore', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('answer', models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('file', models.FileField(default='', upload_to='data')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('runId', models.AutoField(default=10001, primary_key=True, serialize=False)),
                ('submitTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('judgeStatus', models.BooleanField(default='0')),
                ('proId', models.IntegerField(default=1000)),
                ('author', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
