# Generated by Django 2.1.4 on 2020-03-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='averageScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
